"""
src/infra/templates/project_ci.py — CI workflow generator for managed projects.

Generates a GitHub Actions workflow YAML for the project that the orchestrator
is managing. This is NOT the orchestrator's own CI — it is the workflow that
will run inside the target repository and produce the check runs that
SyncGoalPRStatusUseCase polls via the GitHub Checks API.

Why Python instead of a static template file?
  - The job names must exactly match spec.ci.required_checks.
    Generating them programmatically makes that contract impossible to violate.
  - Zero extra dependencies (no Jinja2).
  - The rendered YAML is validated before being written to disk.

Contract (enforced here):
  - Each string in spec.ci.required_checks becomes BOTH the job `id` AND the
    job `name` field.  GitHub's Checks API indexes runs by `name`, which is
    what SyncGoalPRStatusUseCase compares against.
  - The workflow triggers on pushes to goal/** branches (agents push task
    branches there) and on PRs targeting base_branch (the goal-level PR gate).
  - The orchestrator only reads check run results — it never merges PRs.

Usage (called by the GitHub wizard step):
    from src.infra.templates.project_ci import render_project_ci
    yaml_text = render_project_ci(spec.ci, base_branch="main", project_name="myproj")
    (target_repo / ".github/workflows/ci.yml").write_text(yaml_text)
"""
from __future__ import annotations

import textwrap
from typing import Any

import yaml

from src.domain.project_spec.value_objects import CIConfig


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_project_ci(
    ci: CIConfig,
    *,
    base_branch: str = "main",
    project_name: str = "project",
    python_version: str = "3.11",
) -> str:
    """
    Render a complete GitHub Actions workflow YAML for the managed project.

    Parameters
    ----------
    ci            : CIConfig from the project's ProjectSpec.
    base_branch   : Branch that goal PRs target (typically "main").
    project_name  : Human-readable project name used in comments.
    python_version: Python version for the check job runners.

    Returns
    -------
    YAML string, ready to write to .github/workflows/ci.yml in the target repo.

    Raises
    ------
    ValueError if ci.required_checks is empty (a workflow with no jobs is invalid).
    """
    if not ci.required_checks:
        raise ValueError(
            "Cannot render a CI workflow with no required_checks. "
            "Add at least one check name to spec.ci.required_checks before calling "
            "render_project_ci(), or disable the CI gate by not writing a workflow."
        )

    header = _render_header(project_name, base_branch)
    jobs = _render_jobs(list(ci.required_checks), python_version)
    workflow = {**header, "jobs": jobs}

    # yaml.dump with explicit top-level key order
    sections = []
    for key in ("name", "on", "concurrency", "env", "jobs"):
        if key in workflow:
            sections.append(yaml.dump(
                {key: workflow[key]},
                default_flow_style=False,
                sort_keys=(key not in ("on", "jobs")),
                allow_unicode=True,
                indent=2,
            ))

    banner = _banner(project_name, ci, base_branch)
    return banner + "\n".join(sections)


# ---------------------------------------------------------------------------
# Internal builders
# ---------------------------------------------------------------------------

def _banner(project_name: str, ci: CIConfig, base_branch: str = "main") -> str:
    checks_list = ", ".join(ci.required_checks) or "(none)"
    approvals   = ci.min_approvals
    return (
        f"# .github/workflows/ci.yml — CI gate for {project_name}\n"
        "#\n"
        "# Generated by agent-orchestrator `orchestrate init` (Step 6 — GitHub Setup).\n"
        "# DO NOT rename job IDs without also updating project_spec.yaml.\n"
        "#\n"
        "# Naming contract:\n"
        "#   Each job `name:` below must exactly match an entry in\n"
        "#   project_spec.yaml → ci.required_checks.\n"
        "#   The orchestrator's SyncGoalPRStatusUseCase polls these check names\n"
        "#   from the GitHub Checks API.  A mismatch means a goal can never reach\n"
        "#   APPROVED status.\n"
        "#\n"
        f"# Current gate (from project_spec.yaml):\n"
        f"#   required_checks : [{checks_list}]\n"
        f"#   min_approvals   : {approvals}\n"
        "#\n"
        "# To change the gate:\n"
        "#   1. Run:  orchestrate spec propose\n"
        "#   2. Update ci.required_checks / ci.min_approvals in the spec.\n"
        "#   3. Re-run:  orchestrate init --github-only\n"
        "#      (re-renders this file to match the new spec).\n"
        "#\n"
        "# Triggers:\n"
        "#   push  goal/**   — agents push task branches here\n"
        f"#   PR → {base_branch}  — goal-level PR gate polled by the orchestrator\n"
        "\n"
    )


def _render_header(project_name: str, base_branch: str) -> dict[str, Any]:
    return {
        "name": f"CI — {project_name}",
        "on": {
            "push": {
                "branches": ["goal/**"],
            },
            "pull_request": {
                "branches": [base_branch],
            },
        },
        "concurrency": {
            "group": "${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {
            "PYTHON_VERSION": "3.11",
        },
    }


def _render_jobs(required_checks: list[str], python_version: str) -> dict[str, Any]:
    """
    Build one job per required_check name.

    The job id uses the check name with non-alphanumeric chars replaced by '_'
    (GitHub Actions job id rules). The `name:` field is the raw check name —
    that's what the Checks API exposes and what SyncGoalPRStatusUseCase matches.

    Each generated job is intentionally minimal: checkout + Python setup +
    a placeholder run step. The team customises the run step for their stack.
    The placeholder fails loudly so the team cannot accidentally ship a
    green-by-default check.
    """
    jobs: dict[str, Any] = {}

    for check_name in required_checks:
        job_id = _to_job_id(check_name)
        jobs[job_id] = {
            "name": check_name,
            "runs-on": "ubuntu-latest",
            "steps": [
                {"uses": "actions/checkout@v4"},
                {
                    "name": "Set up Python",
                    "uses": "actions/setup-python@v5",
                    "with": {
                        "python-version": "${{ env.PYTHON_VERSION }}",
                        "cache": "pip",
                    },
                },
                {
                    "name": "Install dependencies",
                    "run": (
                        "python -m pip install --upgrade pip\n"
                        "pip install -r requirements.txt\n"
                    ),
                },
                {
                    "name": f"Run {check_name}",
                    # Placeholder: team replaces this with their actual command.
                    # The `false` command ensures CI fails until it's customised.
                    "run": _placeholder_run(check_name),
                },
            ],
        }

    return jobs


def _placeholder_run(check_name: str) -> str:
    return (
        f"# TODO: replace this placeholder with your actual {check_name} command.\n"
        "# Examples:\n"
        "#   pytest tests/ -v --tb=short     (for a \"tests\" check)\n"
        "#   ruff check src/                 (for a \"lint\" check)\n"
        "#   docker build .                  (for a \"build\" check)\n"
        "#\n"
        "# Until you replace this, CI will fail — intentionally.\n"
        f"echo \"Error: {check_name} step not configured. "
        "Edit .github/workflows/ci.yml\" >&2\n"
        "exit 1\n"
    )


def _to_job_id(check_name: str) -> str:
    """Convert a check name to a valid GitHub Actions job id."""
    import re
    return re.sub(r"[^a-zA-Z0-9_-]", "_", check_name).strip("_") or "check"
