"""
src/domain/value_objects/goal.py — Goal value objects.

GoalSpec is the in-memory representation of a validated goal file.
GoalTaskDef describes a single task as declared in that file.

Both are value objects: immutable, validated on construction, no identity
of their own. GoalSpec is the input contract fed to GoalInitUseCase; once
a GoalAggregate exists, these objects are no longer needed at runtime.
"""
from __future__ import annotations

import re
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9\-]*$")


def _assert_slug(value: str, field: str) -> str:
    if not _SLUG_RE.match(value):
        raise ValueError(
            f"'{value}' is not a valid {field}. "
            "Use lowercase letters, digits, and hyphens only (must start with a letter or digit)."
        )
    return value


class GoalTaskDef(BaseModel):
    """
    A single task declaration inside a goal file.

    task_id is a short human-readable slug (e.g. "setup-deps", "add-auth-middleware").
    It becomes the task_id of the created TaskAggregate and the leaf segment
    of the task branch name:  goal/<goal_name>/task/<task_id>.

    All depends_on entries must reference other task_ids within the same GoalSpec.
    """

    task_id: str
    title: str
    description: str
    depends_on: list[str] = Field(default_factory=list)
    capability: str                                         # maps to AgentSelector.required_capability
    files_allowed_to_modify: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    test_command: Optional[str] = None
    max_retries: int = 2
    min_version: str = ">=1.0.0"
    constraints: dict[str, Any] = Field(default_factory=dict)

    @field_validator("task_id")
    @classmethod
    def _validate_task_id(cls, v: str) -> str:
        return _assert_slug(v, "task_id")


class GoalSpec(BaseModel):
    """
    Parsed, validated goal file.

    name is a branch-safe slug used directly in git ref names:
        goal/<name>                     ← goal branch
        goal/<name>/task/<task_id>      ← per-task branch

    Validation enforces:
    - all depends_on references resolve to task_ids within this spec
    - the dependency graph is acyclic (DAG)
    """

    goal_id: Optional[str] = None   # auto-generated by GoalAggregate.create() if absent
    name: str
    description: str
    tasks: list[GoalTaskDef]
    version: str = "1"

    @field_validator("name")
    @classmethod
    def _validate_name(cls, v: str) -> str:
        return _assert_slug(v, "name")

    @model_validator(mode="after")
    def _validate_dag(self) -> "GoalSpec":
        if not self.tasks:
            raise ValueError("A goal must define at least one task.")

        task_ids = {t.task_id for t in self.tasks}

        for task in self.tasks:
            unknown = [d for d in task.depends_on if d not in task_ids]
            if unknown:
                raise ValueError(
                    f"Task '{task.task_id}' depends on {unknown!r} which are "
                    "not defined in this goal spec."
                )

        if _has_cycle({t.task_id: set(t.depends_on) for t in self.tasks}):
            raise ValueError(
                "Task dependency graph contains a cycle. "
                "Check depends_on fields for circular references."
            )

        return self


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _has_cycle(graph: dict[str, set[str]]) -> bool:
    """Return True if the directed graph contains any cycle (DFS)."""
    visited: set[str] = set()
    in_stack: set[str] = set()

    def _dfs(node: str) -> bool:
        visited.add(node)
        in_stack.add(node)
        for dep in graph.get(node, set()):
            if dep not in visited:
                if _dfs(dep):
                    return True
            elif dep in in_stack:
                return True
        in_stack.discard(node)
        return False

    return any(_dfs(n) for n in list(graph) if n not in visited)
