"""
src/domain/value_objects/goal.py — Goal value objects.

GoalSpec is the in-memory representation of a validated goal file.
GoalTaskDef describes a single task as declared in that file.

Both are value objects: immutable, validated on construction, no identity
of their own. GoalSpec is the input contract fed to GoalInitUseCase; once
a GoalAggregate exists, these objects are no longer needed at runtime.
"""
from __future__ import annotations

import re
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9\-]*$")


def _assert_slug(value: str, field: str) -> str:
    if not _SLUG_RE.match(value):
        raise ValueError(
            f"'{value}' is not a valid {field}. "
            "Use lowercase letters, digits, and hyphens only (must start with a letter or digit)."
        )
    return value


class GoalTaskDef(BaseModel):
    """
    A single task declaration inside a goal file.

    task_id is a short human-readable slug (e.g. "setup-deps", "add-auth-middleware").
    It becomes the task_id of the created TaskAggregate and the leaf segment
    of the task branch name:  goal/<goal_name>/task/<task_id>.

    All depends_on entries must reference other task_ids within the same GoalSpec.
    """

    task_id: str
    title: str
    description: str
    depends_on: list[str] = Field(default_factory=list)
    capability: str                                         # maps to AgentSelector.required_capability
    files_allowed_to_modify: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    test_command: Optional[str] = None
    max_retries: int = 2
    min_version: str = ">=1.0.0"
    constraints: dict[str, Any] = Field(default_factory=dict)

    @field_validator("task_id")
    @classmethod
    def _validate_task_id(cls, v: str) -> str:
        return _assert_slug(v, "task_id")


class GoalSpec(BaseModel):
    """
    Parsed, validated goal file.

    name is a branch-safe slug used directly in git ref names:
        goal/<name>                     ← goal branch
        goal/<name>/task/<task_id>      ← per-task branch

    Validation enforces:
    - all depends_on references resolve to task_ids within this spec
    - the dependency graph is acyclic (DAG)
    """

    goal_id: Optional[str] = None   # auto-generated by GoalAggregate.create() if absent
    name: str
    description: str
    tasks: list[GoalTaskDef]
    version: str = "1"

    # Inter-goal dependency: list of other goal *names* this goal depends on.
    # Cross-goal reference validation is the planner's responsibility at the
    # roadmap level — GoalSpec only validates its own internal task DAG.
    depends_on: list[str] = Field(default_factory=list)

    # Feature grouping tag — passed through to GoalAggregate unchanged.
    feature_tag: Optional[str] = None

    @field_validator("name")
    @classmethod
    def _validate_name(cls, v: str) -> str:
        return _assert_slug(v, "name")

    @model_validator(mode="after")
    def _validate_dag(self) -> "GoalSpec":
        if not self.tasks:
            raise ValueError("A goal must define at least one task.")

        task_ids = {t.task_id for t in self.tasks}

        for task in self.tasks:
            unknown = [d for d in task.depends_on if d not in task_ids]
            if unknown:
                raise ValueError(
                    f"Task '{task.task_id}' depends on {unknown!r} which are "
                    "not defined in this goal spec."
                )

        if _has_cycle({t.task_id: set(t.depends_on) for t in self.tasks}):
            raise ValueError(
                "Task dependency graph contains a cycle. "
                "Check depends_on fields for circular references."
            )

        return self


class Roadmap(BaseModel):
    """
    A validated, ordered set of GoalSpecs that form a coherent plan.

    Roadmap is the output contract of the planning layer — it is to goals
    what GoalSpec is to tasks.  Construction fails fast if:

      - any goal's depends_on references a name not present in this roadmap
      - the goal dependency graph contains a cycle
      - two goals share the same name (would produce the same branch ref)

    Immutable after construction.  Use topological_order() to get goals
    in a safe dispatch sequence (dependencies before dependents).

    The planner produces a Roadmap; GoalInitUseCase consumes individual
    GoalSpecs from it.  Nothing else should operate on raw goal lists.
    """

    goals: list[GoalSpec]

    model_config = {"frozen": True}

    @model_validator(mode="after")
    def _validate_goal_dag(self) -> "Roadmap":
        if not self.goals:
            raise ValueError("A roadmap must contain at least one goal.")

        # Duplicate name check — same name → same branch ref → git collision
        names: list[str] = [g.name for g in self.goals]
        seen: set[str] = set()
        for name in names:
            if name in seen:
                raise ValueError(
                    f"Duplicate goal name '{name}' in roadmap. "
                    "Each goal must have a unique name."
                )
            seen.add(name)

        goal_names: set[str] = set(names)

        # Dangling reference check — every depends_on must resolve
        for spec in self.goals:
            unknown = [d for d in spec.depends_on if d not in goal_names]
            if unknown:
                raise ValueError(
                    f"Goal '{spec.name}' depends on {unknown!r} which are "
                    "not defined in this roadmap."
                )

        # Cycle check — reuses the same DFS used by GoalSpec for tasks
        if _has_cycle({g.name: set(g.depends_on) for g in self.goals}):
            raise ValueError(
                "Goal dependency graph contains a cycle. "
                "Check depends_on fields for circular references."
            )

        # Cross-feature dependency guard.
        # Goals in different feature groups must not depend on each other
        # directly — that relationship belongs at the Feature level and will
        # be expressible once FeatureAggregate is introduced.  Enforcing this
        # now keeps the flat Roadmap clean and makes the Feature migration
        # mechanical: each feature_tag group becomes a FeatureSpec, and any
        # inter-feature ordering is declared between FeatureSpecs, not goals.
        feature_of: dict[str, str] = {
            g.name: (g.feature_tag or "") for g in self.goals
        }
        for spec in self.goals:
            for dep in spec.depends_on:
                if feature_of[dep] != feature_of[spec.name]:
                    raise ValueError(
                        f"Goal '{spec.name}' (feature: '{feature_of[spec.name] or 'untagged'}') "
                        f"depends on '{dep}' (feature: '{feature_of[dep] or 'untagged'}'). "
                        "Cross-feature goal dependencies are not yet supported. "
                        "Declare the dependency at the feature level when "
                        "FeatureAggregate is introduced."
                    )

        return self

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def topological_order(self) -> list[GoalSpec]:
        """
        Return goals sorted so every goal appears after all its dependencies.

        Goals with no dependencies come first.  Among goals at the same
        dependency depth the original declaration order is preserved.
        Uses Kahn's algorithm — guaranteed O(V+E), no recursion limit risk.
        """
        from collections import defaultdict, deque

        in_degree: dict[str, int] = {g.name: 0 for g in self.goals}
        dependents: dict[str, list[str]] = defaultdict(list)

        for spec in self.goals:
            for dep in spec.depends_on:
                in_degree[spec.name] += 1
                dependents[dep].append(spec.name)

        by_name = {g.name: g for g in self.goals}
        queue   = deque(n for n, deg in in_degree.items() if deg == 0)
        result: list[GoalSpec] = []

        while queue:
            name = queue.popleft()
            result.append(by_name[name])
            for dep_name in dependents[name]:
                in_degree[dep_name] -= 1
                if in_degree[dep_name] == 0:
                    queue.append(dep_name)

        return result

    def goals_by_feature(self) -> dict[str, list[GoalSpec]]:
        """
        Group goals by feature_tag.  Goals with no tag are grouped under
        the empty string key.  Useful for display and release gating.
        """
        groups: dict[str, list[GoalSpec]] = {}
        for spec in self.goals:
            key = spec.feature_tag or ""
            groups.setdefault(key, []).append(spec)
        return groups

    def goal_names(self) -> set[str]:
        """Return the set of all goal names in this roadmap."""
        return {g.name for g in self.goals}

    def __len__(self) -> int:
        return len(self.goals)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _has_cycle(graph: dict[str, set[str]]) -> bool:
    """Return True if the directed graph contains any cycle (DFS)."""
    visited: set[str] = set()
    in_stack: set[str] = set()

    def _dfs(node: str) -> bool:
        visited.add(node)
        in_stack.add(node)
        for dep in graph.get(node, set()):
            if dep not in visited:
                if _dfs(dep):
                    return True
            elif dep in in_stack:
                return True
        in_stack.discard(node)
        return False

    return any(_dfs(n) for n in list(graph) if n not in visited)
