"""
src/infra/runtime/planner_runtime.py — Planner runtime implementations.

AnthropicPlannerRuntime: Real agentic loop via Anthropic API (claude-opus-4-6).
StubPlannerRuntime: Deterministic stub for tests and dry-run mode.
"""
from __future__ import annotations

import json
from typing import Callable, Optional

from src.domain.ports.planner import (
    PlannerOutput,
    PlannerRuntimeError,
    PlannerRuntimePort,
    PlannerTool,
)
from src.infra.runtime.planners.adapters.anthropic_adapter import AnthropicPlannerAdapter
from src.infra.runtime.planners.base_agent_runtime import BasePlannerRuntime

_DEFAULT_MODEL = "claude-opus-4-6"

_STUB_ROADMAP = {
    "goals": [
        {
            "name": "stub-goal",
            "description": "Stub goal generated by StubPlannerRuntime",
            "tasks": [
                {
                    "task_id": "stub-task",
                    "title": "Stub task",
                    "description": "Placeholder task for dry-run / testing.",
                    "capability": "python",
                    "depends_on": [],
                }
            ],
            "depends_on": [],
            "feature_tag": None,
        }
    ]
}


class AnthropicPlannerRuntime(PlannerRuntimePort):
    """Anthropic planner runtime backed by shared base loop + adapter."""

    def __init__(
        self,
        api_key: str,
        model: str = _DEFAULT_MODEL,
        thinking_budget: int = 8000,
    ) -> None:
        self._runtime = BasePlannerRuntime(
            adapter=AnthropicPlannerAdapter(
                api_key=api_key,
                model=model,
                thinking_budget=thinking_budget,
            ),
            submit_tool_name="submit_final_roadmap",
            artifact_arg="roadmap_json",
        )

    def run_session(
        self,
        prompt: str,
        tools: list[PlannerTool],
        max_turns: int = 15,
        session_callback: Optional[Callable[[str, list[dict]], None]] = None,
        require_submit: bool = True,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> PlannerOutput:
        return self._runtime.run_session(
            prompt=prompt,
            tools=tools,
            max_turns=max_turns,
            session_callback=session_callback,
            require_submit=require_submit,
            cancel_check=cancel_check,
        )


class StubPlannerRuntime(PlannerRuntimePort):
    """
    Deterministic stub that immediately calls submit_final_roadmap.

    Used in dry-run mode and unit tests.  Accepts custom_output to override
    the default stub roadmap.
    """

    def __init__(self, custom_output: Optional[dict] = None) -> None:
        self._custom_output = custom_output or _STUB_ROADMAP

    def run_session(
        self,
        prompt: str,
        tools: list[PlannerTool],
        max_turns: int = 15,
        session_callback: Optional[Callable[[str, list[dict]], None]] = None,
        require_submit: bool = True,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> PlannerOutput:
        tool_map = {t.name: t for t in tools}

        # Architecture mode populates session state via propose tools before
        # the (empty-input) terminal tool reads it back. Drive those first so
        # dry-run architecture sessions produce a usable roadmap.
        if "propose_decision" in tool_map:
            tool_map["propose_decision"].handler(
                {
                    "id": "stub-decision",
                    "domain": "backend",
                    "content": "Stub architecture decision for dry-run.",
                }
            )
        if "propose_phase_plan" in tool_map:
            tool_map["propose_phase_plan"].handler(
                {
                    "phases_json": json.dumps(
                        [
                            {
                                "index": 0,
                                "name": "Foundation",
                                "goal": "Stand up the project skeleton.",
                                "goal_names": ["stub-goal"],
                                "exit_criteria": "Skeleton builds.",
                            }
                        ]
                    )
                }
            )

        terminal = next((t for t in tools if t.terminal), None)
        if terminal is None:
            terminal = tool_map.get("submit_final_roadmap")
        terminal_name = terminal.name if terminal else "submit_final_roadmap"

        roadmap_json = json.dumps(self._custom_output)
        terminal_input = {"roadmap_json": roadmap_json} if terminal_name == "submit_final_roadmap" else {}

        assistant_blocks = [
            {
                "type": "tool_use",
                "id": "stub-tool-1",
                "name": terminal_name,
                "input": terminal_input,
            }
        ]
        if session_callback:
            session_callback("assistant", assistant_blocks)

        result_str = terminal.handler(terminal_input) if terminal else json.dumps({"accepted": True})

        try:
            parsed = json.loads(result_str)
            if not parsed.get("accepted"):
                detail = parsed.get("errors") or parsed.get("error", "unknown error")
                raise PlannerRuntimeError(
                    f"StubPlannerRuntime: {terminal_name} rejected: {detail}"
                )
        except json.JSONDecodeError:
            raise PlannerRuntimeError(f"StubPlannerRuntime: invalid JSON from {terminal_name} handler")

        tool_result_blocks = [
            {
                "type": "tool_result",
                "tool_use_id": "stub-tool-1",
                "content": result_str,
            }
        ]
        if session_callback:
            session_callback("tool_result", tool_result_blocks)

        return PlannerOutput(
            reasoning="Stub reasoning: planning complete.",
            roadmap_raw=self._custom_output,
            raw_text="Stub output: roadmap submitted.",
            turns=[],
            submitted=True,
        )
