"""
src/infra/runtime/planners/stub_planner_runtime.py — Deterministic planner stubs.

Provider-neutral stubs used in dry-run mode and unit tests. They implement
PlannerRuntimePort directly and never touch any provider SDK, so they live
apart from the real OpenAI-backed runtimes.

StubPlannerRuntime: immediately calls the terminal/submit tool.
StubInteractivePlannerRuntime: immediately calls submit_project_brief.
"""
from __future__ import annotations

import json
from typing import Callable, Optional

from src.domain.ports.planner import (
    PlannerOutput,
    PlannerRuntimeError,
    PlannerRuntimePort,
    PlannerTool,
)

# Two valid TDD task defs so dry-run JIT planning actually populates a goal
# (test-writer + implementer), mirroring what the real planner emits via the
# submit_tdd_tasks tool. Without this, dry-run goals stayed at 0 tasks.
_STUB_TDD_TASKS = [
    {
        "task_id": "write-tests",
        "title": "Write failing tests",
        "description": "Stub test-writer task for dry-run.",
        "capability": "code:backend",
        "files_allowed_to_modify": ["tests/*"],
        "depends_on": [],
        "acceptance_criteria": ["Tests fail before implementation."],
        "test_command": None,
    },
    {
        "task_id": "implement",
        "title": "Implement to pass the tests",
        "description": "Stub implementer task for dry-run.",
        "capability": "code:backend",
        "files_allowed_to_modify": ["src/*"],
        "depends_on": ["write-tests"],
        "acceptance_criteria": ["All tests pass."],
        "test_command": "pytest tests/",
    },
]

_STUB_ROADMAP = {
    "goals": [
        {
            "name": "stub-goal",
            "description": "Stub goal generated by StubPlannerRuntime",
            "tasks": [
                {
                    "task_id": "stub-task",
                    "title": "Stub task",
                    "description": "Placeholder task for dry-run / testing.",
                    "capability": "python",
                    "depends_on": [],
                }
            ],
            "depends_on": [],
            "feature_tag": None,
        }
    ]
}


class StubPlannerRuntime(PlannerRuntimePort):
    """
    Deterministic stub that immediately calls submit_final_roadmap.

    Used in dry-run mode and unit tests.  Accepts custom_output to override
    the default stub roadmap.
    """

    def __init__(self, custom_output: Optional[dict] = None) -> None:
        self._custom_output = custom_output or _STUB_ROADMAP

    def run_session(
        self,
        prompt: str,
        tools: list[PlannerTool],
        max_turns: int = 15,
        session_callback: Optional[Callable[[str, list[dict]], None]] = None,
        require_submit: bool = True,
        cancel_check: Optional[Callable[[], bool]] = None,
        prior_turns: Optional[list[dict]] = None,
    ) -> PlannerOutput:
        tool_map = {t.name: t for t in tools}

        # Architecture mode populates session state via propose tools before
        # the (empty-input) terminal tool reads it back. Drive those first so
        # dry-run architecture sessions produce a usable roadmap.
        if "propose_decision" in tool_map:
            tool_map["propose_decision"].handler(
                {
                    "id": "stub-decision",
                    "domain": "backend",
                    "content": "Stub architecture decision for dry-run.",
                }
            )
        if "propose_phase_plan" in tool_map:
            tool_map["propose_phase_plan"].handler(
                {
                    "phases_json": json.dumps(
                        [
                            {
                                "index": 0,
                                "name": "Foundation",
                                "goal": "Stand up the project skeleton.",
                                "goal_names": ["stub-goal"],
                                "exit_criteria": "Skeleton builds.",
                            }
                        ]
                    )
                }
            )

        terminal = next((t for t in tools if t.terminal), None)
        if terminal is None:
            terminal = tool_map.get("submit_final_roadmap")
        terminal_name = terminal.name if terminal else "submit_final_roadmap"

        roadmap_json = json.dumps(self._custom_output)
        if terminal_name == "submit_final_roadmap":
            terminal_input = {"roadmap_json": roadmap_json}
        elif terminal_name == "submit_tdd_tasks":
            # Tactical JIT planning path — supply the two TDD tasks the tool wants.
            terminal_input = {"tasks_json": json.dumps(_STUB_TDD_TASKS)}
        else:
            terminal_input = {}

        assistant_blocks = [
            {
                "type": "tool_use",
                "id": "stub-tool-1",
                "name": terminal_name,
                "input": terminal_input,
            }
        ]
        if session_callback:
            session_callback("assistant", assistant_blocks)

        result_str = terminal.handler(terminal_input) if terminal else json.dumps({"accepted": True})

        try:
            parsed = json.loads(result_str)
            if not parsed.get("accepted"):
                detail = parsed.get("errors") or parsed.get("error", "unknown error")
                raise PlannerRuntimeError(
                    f"StubPlannerRuntime: {terminal_name} rejected: {detail}"
                )
        except json.JSONDecodeError:
            raise PlannerRuntimeError(f"StubPlannerRuntime: invalid JSON from {terminal_name} handler")

        tool_result_blocks = [
            {
                "type": "tool_result",
                "tool_use_id": "stub-tool-1",
                "content": result_str,
            }
        ]
        if session_callback:
            session_callback("tool_result", tool_result_blocks)

        return PlannerOutput(
            reasoning="Stub reasoning: planning complete.",
            roadmap_raw=self._custom_output,
            raw_text="Stub output: roadmap submitted.",
            turns=[],
            submitted=True,
        )


class StubInteractivePlannerRuntime(PlannerRuntimePort):
    """
    For tests. Immediately calls submit_project_brief with a minimal valid
    brief. Does not call ask_question.
    """

    _STUB_BRIEF = {
        "vision": "Stub project vision for testing",
        "constraints": ["no real constraints in stub"],
        "phase_1_exit_criteria": "stub phase 1 done",
        "open_questions": [],
    }

    def __init__(self, custom_brief: Optional[dict] = None) -> None:
        self._custom_brief = custom_brief or self._STUB_BRIEF

    def run_session(
        self,
        prompt: str,
        tools: list[PlannerTool],
        max_turns: int = 15,
        session_callback: Optional[Callable[[str, list[dict]], None]] = None,
        require_submit: bool = True,
        cancel_check: Optional[Callable[[], bool]] = None,
        prior_turns: Optional[list[dict]] = None,
    ) -> PlannerOutput:
        tool_map = {t.name: t.handler for t in tools}
        brief_json = json.dumps(self._custom_brief)

        assistant_blocks = [
            {
                "type": "tool_use",
                "id": "stub-tool-1",
                "name": "submit_project_brief",
                "input": {"brief_json": brief_json},
            }
        ]
        if session_callback:
            session_callback("assistant", assistant_blocks)

        handler = tool_map.get("submit_project_brief")
        result_str = (
            handler({"brief_json": brief_json}) if handler else json.dumps({"accepted": True})
        )

        try:
            parsed = json.loads(result_str)
            if not parsed.get("accepted"):
                raise PlannerRuntimeError(
                    f"StubInteractivePlannerRuntime: submit_project_brief rejected: "
                    f"{parsed.get('error', 'unknown error')}"
                )
        except json.JSONDecodeError:
            raise PlannerRuntimeError(
                "StubInteractivePlannerRuntime: invalid JSON from submit_project_brief handler"
            )

        tool_result_blocks = [
            {
                "type": "tool_result",
                "tool_use_id": "stub-tool-1",
                "content": result_str,
            }
        ]
        if session_callback:
            session_callback("tool_result", tool_result_blocks)

        return PlannerOutput(
            reasoning="Stub reasoning: discovery complete.",
            roadmap_raw=self._custom_brief,
            raw_text="Stub output: project brief submitted.",
            turns=[],
            submitted=True,
        )
