"""
src/infra/runtime/cli_runner.py — CLI agent runners (the async AgentRunner port).

A runner executes ONE task as a one-shot CLI subprocess in the workspace
directory and returns a TaskResult (or raises TaskFailed carrying a typed
FailureKind). It knows NOTHING about retries, backoff or ordering — those are
orchestration decisions; the runner is a pure "execute this task now" hand.

Subclasses supply the command line and environment (pi / claude / gemini —
ported from the pre-refactor runtimes). Subprocess execution is synchronous
but streams stdout/stderr incrementally via process_supervisor.supervise_process
(bounded local log per attempt, process-lifecycle observations persisted
best-effort) rather than blocking on a single communicate() call; the whole
call is hopped off the event loop via asyncio.to_thread so a long agent run
never blocks the worker.

Streamed NDJSON events (the full pi stdio handshake) are roadmap 2.4 — the seam
is isolated in pi_protocol.py; today the sink gets start/finish events plus
the process-lifecycle observations above, so every attempt is observable
end-to-end.
"""

from __future__ import annotations

import asyncio
import os
import time
from abc import ABC, abstractmethod
from pathlib import Path

import structlog

from src.app.ports import AgentEventSink, TaskFailed, WorkspaceHandle
from src.app.runtime_failures import safe_runtime_tail
from src.app.observations import ObservationRepository, ProcessObservationPayload, TelemetryObservation
from src.domain.entities.agent_spec import AgentSpec
from src.domain.entities.task import Task
from src.domain.events.agent_events import AgentEvent
from src.domain.value_objects.tasks_vos import TaskResult
from src.infra.runtime.taxonomy import normalize_failure
from src.infra.runtime.pi_protocol import parse_pi_events
from src.infra.runtime.process_supervisor import (
    attempt_log_path,
    supervise_process,
)

log = structlog.get_logger(__name__)

_OUTPUT_TAIL_CHARS = 8_000  # keep TaskResult.output bounded


def _parse_idempotency_key(
    idempotency_key: str,
) -> tuple[str, str | None, str | None, str | None, str | None, str | None]:
    parts = idempotency_key.split(":")
    if len(parts) != 6:
        return parts[0], None, None, None, None, None
    return parts[0], parts[1], parts[2], parts[3], parts[4], parts[5]


def correlation_env(idempotency_key: str) -> dict[str, str]:
    """Decode the additive execution key into an allowlisted child environment.

    Legacy three-part keys remain valid for direct adapter callers and carry no
    run/attempt correlation. Canonical IDs are generated by ExecutionHandler.
    """
    parsed = _parse_idempotency_key(idempotency_key)
    if parsed[1] is None:
        return {}
    plan_id, goal_id, task_id, run_id, attempt_number, attempt_id = parsed
    assert goal_id is not None
    assert task_id is not None
    assert run_id is not None
    assert attempt_number is not None
    assert attempt_id is not None
    return {
        "ORCHESTRATOR_PLAN_ID": plan_id,
        "ORCHESTRATOR_GOAL_ID": goal_id,
        "ORCHESTRATOR_TASK_ID": task_id,
        "ORCHESTRATOR_RUN_ID": run_id,
        "ORCHESTRATOR_ATTEMPT_NUMBER": attempt_number,
        "ORCHESTRATOR_ATTEMPT_ID": attempt_id,
    }


def build_task_prompt(task: Task, spec: AgentSpec) -> str:
    """Markdown task contract handed to the CLI agent. Project-level conventions
    live in the workspace AGENTS.md — not here — so they apply consistently
    across runtimes."""
    capabilities = ", ".join(task.required_capabilities) or "(none declared)"
    return (
        f"# Task: {task.name}\n\n"
        f"{task.description}\n\n"
        f"## Your role\n{spec.role}\n\n"
        f"## Instructions\n{spec.instructions or '(none)'}\n\n"
        f"## Required capabilities\n{capabilities}\n\n"
        f"---\n"
        f"Task ID: `{task.id}` | Attempt: {task.attempt}"
    )


class CliAgentRunner(ABC):
    """Base for one-shot CLI agent subprocesses."""

    def __init__(
        self,
        timeout_seconds: int = 600,
        *,
        provider_id: str | None = None,
        model_id: str | None = None,
        orchestrator_home: Path | None = None,
        observation_repository: ObservationRepository | None = None,
    ) -> None:
        self._timeout = timeout_seconds
        self._provider_id = provider_id
        self._model_id = model_id
        self._observation_repository = observation_repository
        # Default matches AppContainer.from_env()'s resolution, without
        # constructing a composition root here — CliAgentRunner is an
        # adapter, not the place environment gets read (CLAUDE.md invariant
        # #6). The real wired path (CatalogAgentRunner via container.py)
        # always supplies orchestrator_home explicitly; this default only
        # matters for direct/test construction.
        if orchestrator_home is None:
            orchestrator_home = Path(
                os.environ.get("ORCHESTRATOR_HOME", str(Path.home() / ".orchestrator"))
            )
        self._orchestrator_home = orchestrator_home

    @property
    @abstractmethod
    def log_prefix(self) -> str: ...

    @abstractmethod
    def _build_cmd(self, prompt: str) -> list[str]: ...

    @abstractmethod
    def _env(self) -> dict[str, str]: ...

    async def run(
        self,
        task: Task,
        spec: AgentSpec,
        *,
        idempotency_key: str,
        event_sink: AgentEventSink,
        workspace: WorkspaceHandle,
    ) -> TaskResult:
        plan_id, goal_id, _, run_id, attempt_number_value, attempt_id = (
            _parse_idempotency_key(idempotency_key)
        )
        attempt_number = (
            int(attempt_number_value) if attempt_number_value is not None else task.attempt
        )
        prompt = build_task_prompt(task, spec)
        observations: list[TelemetryObservation] = []

        await self._emit(
            event_sink,
            plan_id=plan_id,
            goal_id=goal_id,
            run_id=run_id,
            attempt_id=attempt_id,
            task_id=task.id,
            attempt=attempt_number,
            seq=0,
            event_type="agent.started",
            payload={
                    "runtime": self.log_prefix,
                    "provider_id": self._provider_id or "",
                    "model_id": self._model_id or "",
                },
        )
        started = time.monotonic()
        try:
            result = await asyncio.to_thread(
                self._run_sync,
                prompt,
                workspace.path,
                correlation_env(idempotency_key),
                observations,
            )
        except TaskFailed as exc:
            await self._persist_observations(observations)
            await self._emit(
                event_sink,
                plan_id=plan_id,
                goal_id=goal_id,
                run_id=run_id,
                attempt_id=attempt_id,
                task_id=task.id,
                attempt=attempt_number,
                seq=1,
                event_type="agent.failed",
                payload={
                    "kind": exc.kind.value if exc.kind else "unknown",
                    "reason": exc.reason[:500],
                    "runtime": exc.failure.runtime or self.log_prefix,
                    "provider_id": exc.failure.provider_id or "",
                    "model_id": exc.failure.model_id or "",
                    "provider_code": exc.failure.provider_code or "",
                    "retryable": str(exc.failure.retryable).lower(),
                    "retry_after_seconds": (
                        str(exc.failure.retry_after_seconds)
                        if exc.failure.retry_after_seconds is not None
                        else ""
                    ),
                    "limit_scope": (
                        exc.failure.limit_scope.value
                        if exc.failure.limit_scope is not None
                        else ""
                    ),
                    "exit_code": (
                        str(exc.failure.exit_code) if exc.failure.exit_code is not None else ""
                    ),
                },
            )
            raise
        await self._persist_observations(observations)
        elapsed = round(time.monotonic() - started, 2)
        seq = 1
        for event_type, payload in self._events_from_output(result.output):
            await self._emit(
                event_sink,
                plan_id=plan_id,
                goal_id=goal_id,
                run_id=run_id,
                attempt_id=attempt_id,
                task_id=task.id,
                attempt=attempt_number,
                seq=seq,
                event_type=event_type,
                payload=payload,
            )
            seq += 1
        await self._emit(
            event_sink,
            plan_id=plan_id,
            goal_id=goal_id,
            run_id=run_id,
            attempt_id=attempt_id,
            task_id=task.id,
            attempt=attempt_number,
            seq=seq,
            event_type="agent.finished",
            payload={"elapsed_seconds": str(elapsed)},
        )
        return result

    async def _emit(
        self,
        event_sink: AgentEventSink,
        *,
        plan_id: str,
        goal_id: str | None,
        run_id: str | None,
        attempt_id: str | None,
        task_id: str,
        attempt: int,
        seq: int,
        event_type: str,
        payload: dict[str, object],
    ) -> None:
        await event_sink.emit(
            AgentEvent(
                plan_id=plan_id,
                goal_id=goal_id,
                run_id=run_id,
                attempt_id=attempt_id,
                task_id=task_id,
                attempt=attempt,
                seq=seq,
                type=event_type,
                payload=payload,
            )
        )

    def _events_from_output(self, output: str) -> list[tuple[str, dict[str, object]]]:
        if not output:
            return []
        return [("runtime.output", {"chunk": safe_runtime_tail(output, 1_000)})]

    async def _persist_observations(self, observations: list[TelemetryObservation]) -> None:
        if self._observation_repository is None:
            return
        for observation in observations:
            try:
                await self._observation_repository.append(observation)
            except Exception:
                log.warning(
                    "runtime.process_observation_persist_failed",
                    observation_id=observation.observation_id,
                    exc_info=True,
                )

    def _run_sync(
        self,
        prompt: str,
        cwd: str,
        execution_env: dict[str, str],
        observations: list[TelemetryObservation],
    ) -> TaskResult:
        cmd = self._build_cmd(prompt)
        log.info(f"{self.log_prefix}.running", cwd=cwd, timeout=self._timeout)
        def on_observation(observation: TelemetryObservation) -> None:
            observations.append(observation)
            log.info(
                "runtime.process_observation",
                kind=observation.kind.value,
                source=observation.source.value,
                payload=(
                    {
                        "stdout_bytes": observation.payload.stdout_bytes,
                        "stderr_bytes": observation.payload.stderr_bytes,
                        "exit_code": observation.payload.exit_code,
                        "duration_seconds": observation.payload.duration_seconds,
                        "log_path": observation.payload.log_path,
                    }
                    if isinstance(observation.payload, ProcessObservationPayload)
                    else {}
                ),
            )

        try:
            attempt_id = execution_env.get("ORCHESTRATOR_ATTEMPT_ID")
            result = supervise_process(
                cmd,
                cwd=cwd,
                env={**self._env(), **execution_env},
                timeout_seconds=self._timeout,
                log_path=(
                    attempt_log_path(self._orchestrator_home, attempt_id)
                    if attempt_id is not None
                    else None
                ),
                on_observation=on_observation,
                plan_id=execution_env.get("ORCHESTRATOR_PLAN_ID", "runtime"),
                goal_id=execution_env.get("ORCHESTRATOR_GOAL_ID"),
                task_id=execution_env.get("ORCHESTRATOR_TASK_ID"),
                run_id=execution_env.get("ORCHESTRATOR_RUN_ID"),
                attempt_id=execution_env.get("ORCHESTRATOR_ATTEMPT_ID"),
                attempt_number=(
                    int(execution_env["ORCHESTRATOR_ATTEMPT_NUMBER"])
                    if "ORCHESTRATOR_ATTEMPT_NUMBER" in execution_env
                    else None
                ),
            )
        except FileNotFoundError as exc:
            failure = normalize_failure(
                stderr=str(exc),
                runtime=self.log_prefix,
                provider_id=self._provider_id,
                model_id=self._model_id,
            )
            raise TaskFailed(
                f"{self.log_prefix} CLI not found: {cmd[0]!r}", failure=failure
            ) from exc

        if result.timed_out:
            failure = normalize_failure(
                timed_out=True,
                runtime=self.log_prefix,
                provider_id=self._provider_id,
                model_id=self._model_id,
            )
            raise TaskFailed(
                f"{self.log_prefix} timed out after {self._timeout}s",
                failure=failure,
            )

        stdout, stderr = result.stdout, result.stderr
        if result.exit_code != 0:
            failure = normalize_failure(
                stdout=stdout,
                stderr=stderr,
                runtime=self.log_prefix,
                provider_id=self._provider_id,
                model_id=self._model_id,
                exit_code=result.exit_code,
            )
            log.warning(
                f"{self.log_prefix}.failed",
                exit_code=result.exit_code,
                kind=failure.kind.value,
            )
            raise TaskFailed(failure.safe_message, failure=failure)

        log.info(f"{self.log_prefix}.finished", exit_code=0, log_path=str(result.log_path))
        return TaskResult.success(
            stdout[-_OUTPUT_TAIL_CHARS:],
            metadata={
                "runtime": self.log_prefix,
                "exit_code": "0",
                "cleanup": "complete",
                "log_path": str(result.log_path),
                "stdout_bytes": str(result.stdout_bytes),
                "stderr_bytes": str(result.stderr_bytes),
            },
        )


# Backend -> the env var pi reads for that provider (pi's env-api-keys.ts).
PI_BACKEND_ENV_VAR: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "gemini": "GEMINI_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
}


class PiAgentRunner(CliAgentRunner):
    """Runs `pi --model <m> -p "<prompt>"` in the workspace (pi-mono CLI)."""

    def __init__(
        self,
        api_key: str,
        model: str,
        backend: str = "anthropic",
        extra_flags: list[str] | None = None,
        timeout_seconds: int = 600,
        provider_id: str | None = None,
        model_id: str | None = None,
        orchestrator_home: Path | None = None,
        observation_repository: ObservationRepository | None = None,
    ) -> None:
        if backend not in PI_BACKEND_ENV_VAR:
            raise ValueError(
                f"Invalid pi backend '{backend}'. Valid: {', '.join(sorted(PI_BACKEND_ENV_VAR))}"
            )
        if not api_key:
            raise ValueError(f"PiAgentRunner requires an api_key for backend '{backend}'")
        super().__init__(
            timeout_seconds,
            provider_id=provider_id,
            model_id=model_id,
            orchestrator_home=orchestrator_home,
            observation_repository=observation_repository,
        )
        self._api_key = api_key
        self._model = model
        self._backend = backend
        self._extra_flags = extra_flags or []

    @property
    def log_prefix(self) -> str:
        return "pi"

    def _build_cmd(self, prompt: str) -> list[str]:
        return ["pi", "--model", self._model, "-p", prompt, *self._extra_flags]

    def _env(self) -> dict[str, str]:
        return {**os.environ, PI_BACKEND_ENV_VAR[self._backend]: self._api_key}

    def _events_from_output(self, output: str) -> list[tuple[str, dict[str, object]]]:
        structured = parse_pi_events(output)
        return structured or super()._events_from_output(output)


class ClaudeCodeRunner(CliAgentRunner):
    """Runs `claude --dangerously-skip-permissions -p "<prompt>"`."""

    def __init__(
        self,
        api_key: str,
        model: str | None = None,
        extra_flags: list[str] | None = None,
        timeout_seconds: int = 600,
        provider_id: str | None = None,
        model_id: str | None = None,
        orchestrator_home: Path | None = None,
        observation_repository: ObservationRepository | None = None,
    ) -> None:
        super().__init__(
            timeout_seconds,
            provider_id=provider_id,
            model_id=model_id,
            orchestrator_home=orchestrator_home,
            observation_repository=observation_repository,
        )
        self._api_key = api_key
        self._model = model
        self._extra_flags = extra_flags or []

    @property
    def log_prefix(self) -> str:
        return "claude"

    def _build_cmd(self, prompt: str) -> list[str]:
        cmd = ["claude", "--dangerously-skip-permissions", "-p", prompt]
        if self._model:
            cmd += ["--model", self._model]
        return cmd + self._extra_flags

    def _env(self) -> dict[str, str]:
        return {**os.environ, "ANTHROPIC_API_KEY": self._api_key}


class GeminiRunner(CliAgentRunner):
    """Runs `gemini --model=<m> --yolo -p "<prompt>"`."""

    def __init__(
        self,
        api_key: str,
        model: str,
        extra_flags: list[str] | None = None,
        timeout_seconds: int = 600,
        provider_id: str | None = None,
        model_id: str | None = None,
        orchestrator_home: Path | None = None,
        observation_repository: ObservationRepository | None = None,
    ) -> None:
        super().__init__(
            timeout_seconds,
            provider_id=provider_id,
            model_id=model_id,
            orchestrator_home=orchestrator_home,
            observation_repository=observation_repository,
        )
        self._api_key = api_key
        self._model = model
        self._extra_flags = extra_flags or []

    @property
    def log_prefix(self) -> str:
        return "gemini"

    def _build_cmd(self, prompt: str) -> list[str]:
        return [
            "gemini",
            f"--model={self._model}",
            "--yolo",
            "-p",
            prompt,
            *self._extra_flags,
        ]

    def _env(self) -> dict[str, str]:
        return {
            **os.environ,
            "GEMINI_API_KEY": self._api_key,
            "GEMINI_MODEL": self._model,
        }
