"""Which task failures are worth telling the next agent attempt about.

A retry today re-runs an identical prompt against an identical contract on a
clean worktree, so it reproduces the identical failure. Feeding the rejection
back is what makes a retry mean anything — and it is the precondition for ever
making a verification failure retryable at all.

Not every failure belongs in a prompt. Three classes:

  A  agent-repairable — the candidate the agent produced was rejected: out of
     scope, protected test touched, no RED, the authoritative command failed.
     Retrying works if and only if the agent is told which one.
  B  contract-unsatisfiable — the scope matches nothing, the command names a
     file that cannot exist. No agent can succeed; repeating the prompt is pure
     spend. (Repairing the contract is the answer — a later phase.)
  C  orchestration invariants — a superseded cycle, evidence that changed during
     promotion, an unavailable verifier. These are races and infrastructure, not
     the agent's work. Showing them to an agent invites it to "fix" something it
     has no business touching.

The discriminator here is a whitelist of the messages the CANDIDATE path itself
emits (`src/app/verification.py` and the two finalize functions in the execution
handler). That is not heuristic string-sniffing of foreign text: these strings
are generated by this codebase, in one place each, and the test suite pins them.
It stays a prompt-shaping decision only — when RETRYABILITY comes to depend on
the A/B/C split, that split needs to be structural (carried on the failure
itself), because a wrong guess there costs provider spend rather than a slightly
less useful paragraph.
"""

from __future__ import annotations

# Prefixes of the rejections a task attempt produces about the agent's own
# candidate. Each is emitted at exactly one site; see the tests for the map.
_AGENT_ACTIONABLE_PREFIXES: tuple[str, ...] = (
    # src/app/verification.py -> validate_candidate reasons
    "path outside allowed scope",
    "forbidden path changed",
    "protected test changed",
    "protected test missing or renamed",
    "test bypass marker present",
    "verification configuration changed",
    "test bundle does not match task revision",
    # execution_handler._finalize_test_author
    "test author produced no executable checks",
    "test author modified production paths",
    "test author deleted or renamed executable checks",
    "test bundle did not establish",
    "verification command modified production paths",
    # execution_handler._finalize_verified_implementation
    "authoritative verification command failed",
    "verification command changed the validated candidate",
)


def is_agent_actionable(message: str | None) -> bool:
    """True when this failure describes something the agent itself can fix."""
    if not message:
        return False
    text = message.strip()
    # A rejection may be several reasons joined with "; " — the first one decides,
    # since validate_candidate emits them as a homogeneous group.
    return text.startswith(_AGENT_ACTIONABLE_PREFIXES)


def split_reasons(message: str) -> list[str]:
    """The individual rejection reasons inside one joined failure message."""
    return [part.strip() for part in message.split("; ") if part.strip()]


__all__ = ["is_agent_actionable", "split_reasons"]
